### ISSUE TITLE
Issue on copying directory with midnight commander on linux

### ISSUE THREAD

**Issue by cristiur** [eduardsui/edwork#1]
Error on adding directory with midnight commander on linux.
The error returned from midnight commander is "Numerical result out of range (34)"
The error in edwork console is:  "fuse: bad error value: 40"

The solution on windows was to ignore the error on function edfs_fuse_mkdir in file edfs_fuse.c
(ie: function always return 0)

I have applied the same solution on linux and now it's working. Don't know if it's the correct solution, but now it's working.

**Comment by eduardsui** [comment]
Solved by [2d45657](https://github.com/eduardsui/edwork/commit/2d4565797b0be0cc56ca0a74744b6bf4f489fd4a) .
