### ISSUE TITLE
Cleanning local files on deleting large file from the partition

### ISSUE THREAD

**Issue by cristiur** [eduardsui/edwork#2]
It is possible to clean the local files when a large file is removed from the network ?
Or this is done automatically? 

I am thinking about a shard server after a while.
 
How this is working ?

**Comment by eduardsui** [comment]
The inode data chunks are automatically removed on delete event from every node. Only the inode metadata (the signed-json file) is kept for versioning reasons. If you want to delete the json file, you need to compile it with -DEDFS_USE_HARD_DELETE. Not that this is not compatible with versioning control.
