### ISSUE TITLE
The windows client is broken (version 1.2.6)

### ISSUE THREAD

**Issue by cristiur** [eduardsui/edwork#3]
I upload from windows in edwork directory 3 files (~200MB each ) and the size on windows is different from linux.

file1 - windows: (199,070,150 bytes)  linux: 198532480 bytes
file2 - windows: (197,406,163 bytes)  linux: 196871360 bytes
same with file 3

if i restart the windows node , the size is the same as linux, but is the wrong size.

All the nodes runs the latest version.

**Comment by cristiur** [comment]
The behavior is observed with big files. Small files are ok.

**Comment by eduardsui** [comment]
Fixed by [89c1c9e](https://github.com/eduardsui/edwork/commit/89c1c9e6c003cf0201657d0d7a6c7ff9e2943602)
